version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/custom-logs
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myapp
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./node-api
    ports:
      - "4000:4000"
    env_file:
      - .env
    working_dir: /usr/src/app
    volumes:
      - ./node-api:/usr/src/app
    command: ["node", "index.js"]


volumes:
  db_data:
